name: "Build amd64"

on:
  workflow_dispatch:
  schedule:
# Build Every Week
    - cron: "0 0 * * 0"
  push:
    branches: [ 'main' ]
    paths:
      - "build-*.sh"
      - ".github/workflows/*.yml"
      - "wslconf/*"

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: start build
        run: |
          bash build-stable.sh
          bash build-edge.sh
      - name: Push to release stable
        uses: softprops/action-gh-release@v3
        with:
          tag_name: release-${{ env.ARCH }}-${{ env.RELEASE }}
          name: Release ${{ env.ARCH }} ${{ env.RELEASE }}
          files: |
            alpine.wsl
          preserve_order: true
          make_latest: true
      - name: Push to release edge
        uses: softprops/action-gh-release@v3
        with:
          tag_name: release-${{ env.ARCH }}-${{ env.RELEASE_EDGE }}
          name: Release ${{ env.ARCH }} ${{ env.RELEASE_EDGE }}
          files: |
            alpine-edge.wsl
          preserve_order: true
          make_latest: true

env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}