name: Build Zip CI

permissions:
  contents: write

on:
  push:
    branches: [ 'main' ]
    paths:
      - 'src_x64/**'
      - 'src_arm64/**'
  pull_request: 
    branches: [ 'main' ]
    paths:
      - 'src_x64/**'
      - 'src_arm64/**'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Install dependencies for build (Apt)
      shell: bash
      run: |
        sudo env DEBIAN_FRONTEND=noninteractive apt update -y && \
        sudo env DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends libarchive-tools curl jq tree
    - name: Build Zip x64
      shell: bash
      env:
        ARCH: 'x64'
        OUT_ZIP: 'Alpine-Edge.zip'
      run: |
        make -e
        sha256sum Alpine-Edge.zip | tee Alpine-Edge.zip.sha256
        ls -la
    - name: Build Zip ARM64
      shell: bash
      env:
        ARCH: 'arm64'
        OUT_ZIP: 'Alpine-Edge_arm64.zip'
      run: |
        make -e
        sha256sum Alpine-Edge_arm64.zip | tee Alpine-Edge_arm64.zip.sha256
        ls -la
    - name: Upload a Build Artifact x64
      uses: actions/upload-artifact@main
      with:
        name: Alpine-Edge.zip
        path: ./Alpine-Edge.zip
    - name: Upload SHA256 Checksum x64
      uses: actions/upload-artifact@main
      with:
        name: Alpine-Edge.zip.sha256
        path: ./Alpine-Edge.zip.sha256
    - name: Upload a Build Artifact ARM64
      uses: actions/upload-artifact@main
      with:
        name: Alpine-Edge_arm64.zip
        path: ./Alpine-Edge_arm64.zip
    - name: Upload SHA256 Checksum ARM64
      uses: actions/upload-artifact@main
      with:
        name: Alpine-Edge_arm64.zip.sha256
        path: ./Alpine-Edge_arm64.zip.sha256
